### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [xdid-net/gtm-append#1]
https://github.com/xdid-net/gtm-append/blob/faefcf416f32b67d6706866083602a7c6405b58b/template.tpl#L55

When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by xdid-net** [comment]
Fixed with new version
